### ISSUE TITLE
Workspace conflicts

### ISSUE THREAD

**Issue by cdvillard** [bencodezen/bens-obsidian-boilerplate#1]
Looking into the `.obsidian` folders and it seems there are several conflicted workspace files. Not sure if that breaks anything, but it looks like there is personal data already in there. [This is one of several such files](https://github.com/bencodezen/obsidian-starter-kit/blob/main/.obsidian/workspace%20(Benjamin%20Hong's%20conflicted%20copy%202021-01-08)) in `/.obsidian/`.

**Comment by bencodezen** [comment]
Ahh so sorry for the delay in seeing this. Thanks for letting me know and I'll keep an eye out for this in the future!
